language: python

services:
- docker

before_install: 
 - docker build -t pandapanda .
 - docker run --rm -p 127.0.0.1:5000:5000 --name pandapanda pandapanda -m unittest test_randomfact functional_tests

