language: python
python:
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.5-dev"
 - "3.6"
 - "3.6-dev"
 - "3.7-dev"
 - "nightly"

install: "pip install -r requirements.txt"
 - docker build -t pandapanda .
 - docker run -d -p -p 127.0.0.1:80:80 --name pandapanda

script: 
 - docker ps | grep -q pandapanda
 - python -m unittest test_randomfact.py
